[package]
name = "femirad"
version = "0.1.0"
authors = ["johnm <trolledwoods@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
glam = "0.17.3"
rayon = "1.5.1"
